@startuml
hide circle
left to right direction
scale 3
class "学生" as s {
	名前
}

class "講義" as l {
	名前
    曜日
    コマ
}

class "時間割" as t {
}

s "0..*" -- "0..*" l : "履修する >"
t o--> "0..*" l
s "1" *-- "1" t

@enduml
