@startuml
hide circle
left to right direction
scale 2
class "Students" as s {
	name: String

    getName(): String
    take(lec: Lectures): void
    printSchedule(): void
}

class "Lectures" as l {
	name: String
    day: int
    slot: int

    getName(): String
    getDay(): int
    getSlot(): int
    regist(student: Students): void
    printMeibo(): void
}

class "Schedule" as t {

	set(day: int, slot: int, lec: Lectures): void
    print(): void
}

s "0..200 \n myStudent" <--- l
t "0..*" o---> "0..25 \n table" l
s "1" *---> "1 \n mySchedule" t
s .....> l
@enduml
