@startuml
scale 1.5
left to right direction

actor :ユーザ: as user
actor :ヒーター: as heater
actor :サーミスタ: as thermo
actor :ポンプ: as pump
actor :タイマー: as timer

usecase (保温する) as keep
usecase (沸騰する) as boil
usecase (給湯する) as pour
usecase (タイマーを使う) as use_timer

user -- boil
user -- pour
user -- use_timer
boil -- heater
keep -- heater
boil -- thermo
keep -- thermo
pour -- pump
use_timer -- timer
@enduml
